### ISSUE TITLE
Can't seed data for local development.

### ISSUE THREAD

**Issue by oibind** [apoclyps/my-dev-space#337]
**Describe the bug**
On trying to setup a local development environment can't complete the last command due to apparent code issue.

**To Reproduce**

1. Try to run: `docker-compose -f docker-compose-dev.yml run events-service python manage.py seed_db`
2. Fails
3. Error output- 

$ docker-compose -f docker-compose-dev.yml run events-service python manage.py seed_db
WARNING: The CI variable is not set. Defaulting to a blank string.
Starting events-db ... done
Traceback (most recent call last):
  File "manage.py", line 136, in <module>
    manager.run()
  File "/usr/local/lib/python3.7/site-packages/flask_script/__init__.py", line 417, in run
    result = self.handle(argv[0], argv[1:])
  File "/usr/local/lib/python3.7/site-packages/flask_script/__init__.py", line 386, in handle
    res = handle(*args, **config)
  File "/usr/local/lib/python3.7/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "manage.py", line 85, in seed_db
    Topic(name="Python", description="", abbreviation="py"),
NameError: name 'Topic' is not defined

**Expected behavior**
Seed data to the database

**Comment by apoclyps** [comment]
@oibind thank you for submitting this issue; I've reproduced the issue locally and identified the origin of the issue within #253. The database remodeling that occurred in that ticket included breaking changes to the `seed_db` command, which has now been deprecated and replaced with the `load_data` script. 

#338 provides updated instructions on how to populate a local database using the `load_data` script.
